font_size 14.0
background_opacity 0.9
touch_scroll_multiplier 2.0
window_padding_width 4
disable_ligatures always
allow_remote_control yes

cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

map ctrl+backspace send_text all \x17

background #181825
foreground #fdfff1
selection_background #fdfff1
selection_foreground #3b3c35
cursor #eccf4f

color0 #343835
color1 #ce3e60
color2 #7bb75b
color3 #e8b32a
color4 #4c99d3
color5 #a57fc4
color6 #389aac
color7 #f9faf6
color8 #585a58
color9 #d18ae6
color10 #767e2b
color11 #77592e
color12 #135879
color13 #5f4190
color14 #76bbca
color15 #b1b5ae


# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
