[widgets]
enabled = true

[panel]
enabled = true
spacing = 10
# thickness = 0
position = "bottom"
modules_left = ["workspaces"]
modules_center = []
modules_right = ["keymap", "battery", "clock"]

[panel.battery]
icons = ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
name = "BAT1"
format = "ahah {icon} {charge}%"

[panel.clock]
format = "%a %e %b %H:%M"
# format = "%H:%M"

[launcher]
enabled = true
placeholder = "let's find something..."
terminal_cmd = "kitty"
detach = true
