[widgets]
enabled = true

[panel]
enabled = true
spacing = 10
# thickness = 0
position = "top"
modules_left = ["workspaces"]
modules_center = []
modules_right = ["keyboard_layout", "pulseaudio", "clock"]

[panel.battery]
icons = ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
name = "BAT1"
# format = "ahah {icon} {charge}%"

[panel.clock]
format = "%a %e %b %H:%M"
# format = "%H:%M"

[panel.workspaces]
numeral_system = "japanese"
# numeral_variant = "financial"
