searchbar_placeholder = "Search..."
providers = ["applications", "wallpapers"]

[applications]
terminal_cmd = "kitty"
detach = false

[wallpapers]
path = "/home/inqlog/Pictures/backgrounds/0-favorite"
change_command = """
awww img --transition-fps 120 \
  --transition-type center \
  --transition-duration 0.8 \
  --transition-step 40 \
  --transition-bezier 0.42,0.0,1.0,1.0 \
  {{image}}
"""

matugen = true
matugen_flags = [
  "--source-color-index",
  "0",
  "--type",
  "scheme-fidelity",
  "--fallback-color",
  "#808080",
]
