enabled = true
spacing = 10
# thickness = 0
position = "top"

[modules]
left = ["workspaces"]
center = []
right = ["keyboard_layout", "pulseaudio", "clock"]

[battery]
icons = ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
name = "BAT1"
# format = "ahah {icon} {charge}%"

[clock]
format = "%a %e %b %H:%M"
# format = "%H:%M"

[workspaces]
numeral_system = "japanese"
# numeral_variant = "financial"
