spacing = 10
# thickness = 0
position = "top"

[modules]
left = ["workspaces", "separator"]
center = []
right = ["keyboard_layout", "separator", "pulseaudio", "separator", "clock"]

[battery]
icons = ["󰂎", "󰁺", "󰁻", "󰁼", "󰁽", "󰁾", "󰁿", "󰂀", "󰂁", "󰂂", "󰁹"]
name = "BAT1"
# format = "ahah {icon} {charge}%"

[clock]
format = "%a, %b %e %H:%M"
# format = "%H:%M"

[workspaces]
# numeral_system = "japanese"
# numeral_variant = "financial"
