monitor=DP-1,1920x1080@143.60Hz,0x0,1

$terminal = kitty
$fileManager = nautilus
$hyprpicker = hyprpicker -a --format=rgb -t -d
$launcher = chameleon -t

### AUTOSTART ###
exec-once = awww-daemon
exec-once = hypridle
exec-once = hyprsunset
exec-once = chameleon -c ~/.config/chameleon/stable-config.toml
exec-once = waybar
exec-once = $terminal
exec-once = systemctl --user start hyprpolkitagent

### ENVIRONMENT VARIABLES ###
env = XCURSOR_THEME,MacTahoe-dark
env = XCURSOR_SIZE,28

env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_STYLE_OVERRIDE,kvantum

env = ELECTRON_OZONE_PLATFORM_HINT,wayland
# env = GDK_BACKEND,wayland


general {
    gaps_in = 5
    gaps_out = 5,10,8,10
    border_size = 0

    col.active_border = rgba(46474ccc)
    col.inactive_border = rgba(46474ccc)

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 4
    rounding_power = 4

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 8
        render_power = 3
        color = rgba(22, 22, 22, 0.7)
        offset = 0 1
        scale = 1.0
    }

    blur {
        enabled = true
        size = 2
        passes = 3
        popups = true
        popups_ignorealpha = 0.3
        noise = 0.02
        vibrancy = 1
        contrast = 0.6
    }
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = slave
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

input {
    kb_layout = us,ru
    kb_options = caps:swapescape, grp:shifts_toggle
    follow_mouse = 1
    sensitivity = -0.9 # -1.0 - 1.0, 0 means no modification.
    scroll_factor = 1

    touchpad {
        natural_scroll = true
    }
}

binds {
    scroll_event_delay = 100
    workspace_back_and_forth = false
    allow_workspace_cycles = false
    movefocus_cycles_fullscreen = false
}

gestures {

}

device {
    name = logitech-g102-lightsync-gaming-mouse
    repeat_rate = 50
    repeat_delay = 500
    middle_button_emulation = 0
}

xwayland {
  force_zero_scaling = true
}

source = ~/.config/hypr/hyprland/animations.conf
source = ~/.config/hypr/hyprland/keybindings.conf
source = ~/.config/hypr/hyprland/windowrules.conf
source = ~/.config/hypr/hyprland/gestures.conf
