### --- WINDOWS --- ###

# Ignore maximize requests from all apps. You'll probably like this.
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Terminal Border
windowrule {
    name = terminal-border
    match:class = (kitty|com.mitchellh.ghostty)

    border_size = 1
}

# Steam
windowrule {
    name = steam
    match:class = steam

    rounding = 0
    no_shadow = true
}


# Screenshare in chrome
windowrule {
    name = chrome-screenshare

    match:title = (Приложение .* предоставило доступ к окну.|Приложению .* предоставлен доступ к вашему экрану.)

    no_blur = true
    no_shadow = true
}

# Code popup
windowrule {
    name = vscode-popup
    match:title = ^(Visual Studio Code|Code - OSS)$
    match:class = ^(code|electron)$
    match:float = true

    no_shadow = true
    no_blur = true
    rounding = 14
}

# Pavucontrol
windowrule {
    name = pavucontrol
    match:class = ^org.pulseaudio.pavucontrol$

    size = 900 600
    center = true
    float = true
}

# File Picker
windowrule {
    name = gtk-file-picker
    match:class = ^xdg-desktop-portal-gtk$

    float = true
    center = true
    size = 1080 800
}

# Amnezia VPN
windowrule {
    name = amnezia
    match:class = AmneziaVPN

    size = 600 800
    float = true
    rounding = 0
    no_blur = true
}

# Throne
windowrule {
    name = throne
    match:class = Throne

    size = 90% 90%
    float = true
}

# Telegram
windowrule {
    name = telegram
    match:class = org.telegram.desktop

    size = 90% 90%
    float = true
}

# Megabonk
windowrule {
    name = fix-megabonk-scroll-factor
    match:class = ^Megabonk.x86_64$
    match:title = ^Megabonk$

    scroll_mouse = 10
}

# VirtualBox
windowrule {
    name = virtual-box
    match:class = ^VirtualBox Machine$

    no_blur = false
}


### --- LAYERS --- ###
layerrule {
    name = chameleon
    match:namespace = chameleon-taskbar

    blur = true
    blur_popups = true
    ignore_alpha = 0.2
}

layerrule {
    name = chameleon
    match:namespace = chameleon-launcher

    blur = true
    blur_popups = true
    ignore_alpha = 0.2
}

layerrule {
    name = waybar
    match:namespace = waybar

    blur = true
    blur_popups = true
    ignore_alpha = 0.2
}