### WINDOWS ###

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = bordersize 1, class:kitty
windowrule = bordersize 1, class:com.mitchellh.ghostty

windowrule = rounding 0, class:steam
windowrule = noshadow, class:steam

# Screenshare in chrome
windowrule = noshadow, title:Приложение .* предоставило доступ к окну.
windowrule = noblur, title:Приложение .* предоставило доступ к окну.

windowrule = noshadow, title:Приложению .* предоставлен доступ к вашему экрану.
windowrule = noblur, title:Приложению .* предоставлен доступ к вашему экрану.

# Code popup
windowrule = noshadow, title:^(Visual Studio Code|Code - OSS)$, class:^(code|electron)$, floating:1
windowrule = noblur, title:^(Visual Studio Code|Code - OSS)$, class:^(code|electron)$, floating:1
windowrule = rounding 14, title:^(Visual Studio Code|Code - OSS)$, class:^(code|electron)$, floating:1

# Pavucontrol
windowrule = float, class:^org.pulseaudio.pavucontrol$
windowrule = center, class:^org.pulseaudio.pavucontrol$
windowrule = size 900 600, class:^org.pulseaudio.pavucontrol$

windowrule = float, class:^xdg-desktop-portal-gtk$
windowrule = center, class:^xdg-desktop-portal-gtk$
windowrule = size 1080 800, class:^xdg-desktop-portal-gtk$

### LAYERS ###
layerrule = blur, chameleon-taskbar
layerrule = blurpopups, chameleon-taskbar
layerrule = ignorealpha 0.2, chameleon-taskbar

layerrule = blur, waybar
layerrule = blurpopups, waybar
layerrule = ignorealpha 0.2, waybar