[colors.primary]
background = "#1d1d1d"
foreground = "#f7f6ec"

[colors.cursor]
cursor = "#eccf4f"
# text = "#1d1d1d"   # цвет текста под курсором

[colors.selection]
background = "#165776"
text = "#1d1d1d"

[colors.normal]
black = "#343835"
red = "#ce3e60"
green = "#7bb75b"
yellow = "#e8b32a"
blue = "#4c99d3"
magenta = "#a57fc4"
cyan = "#389aac"
white = "#f9faf6"

[colors.bright]
black = "#585a58"
red = "#d18ea6"
green = "#767e2b"
yellow = "#77592e"
blue = "#135879"
magenta = "#5f4190"
cyan = "#76bbca"
white = "#b1b5ae"
