[general]
import = ["~/.config/alacritty/themes/myown.toml"]
ipc_socket = false

[window]
decorations = "None"
opacity = 0.9
blur = true
padding = { x = 12, y = 8 }
dynamic_padding = false
dynamic_title = false

[scrolling]
history = 10000
multiplier = 2

[font]
size = 14
normal = { family = "CaskaydiaMono Nerd Font", style = "Medium" }
bold = { family = "CaskaydiaMono Nerd Font", style = "SemiBold" }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500

[mouse]
hide_when_typing = true
