[general]
import = ["~/.config/alacritty/ferra.toml"]
ipc_socket = false

[window]
decorations = "None"
opacity = 1
blur = false
padding = { x = 12, y = 8 }
dynamic_padding = true
dynamic_title = false

[scrolling]
history = 10000
multiplier = 2

[font]
size = 15.5
normal = { family = "CaskaydiaMono Nerd Font", style = "Medium" }
bold = { family = "CaskaydiaMono Nerd Font", style = "SemiBold" }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500

[mouse]
hide_when_typing = true
