theme = "vscode-light"

[editor]
scrolloff = 3
mouse = false
true-color = true
undercurl = true
line-number = "relative"
bufferline = "multiple"
clipboard-provider = "wayland"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true

[editor.statusline]
left = ["mode", "diagnostics", "version-control", "spinner"]
center = []
right = ["position", "total-line-numbers", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]


### KEYS ###
[keys.normal]
# ";" = "command_mode"
C-s = ":write"
C-g = [":new", ":insert-output lazygit", ":buffer-close", ":redraw"]
