theme = "gruvbox-material"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "diagnostics", "spinner"]
center = []
right = ["file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]


### KEYS ###
[keys.normal]
# ";" = "command_mode"
C-s = ":write"
C-g = [":new", ":insert-output lazygit", ":buffer-close", ":redraw"]
