[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "go"
auto-format = true

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
