[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "vue"
auto-format = false
language-servers = ["typescript-language-server"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/usr/lib/node_modules/@vue/typescript-plugin"
languages = ["vue"]
